
```{r, include = F}
library(tidyverse)
library(tinythemes)
theme_set(tinythemes::theme_ipsum_rc())
```


```{r, include=F}
country = params$country
d = read_tsv("../_data/posts.tsv.gz") |> 
  filter(country == params$country) |> 
  filter(timestamp >= as.Date("2025-03-15")) |> 
  filter(timestamp < as.Date("2025-04-15"))
```

```{r}
n_posts = nrow(d)
n_outlets = n_distinct(d$brand)
n_days = n_distinct(as.Date(d$timestamp))
per_day = round(n_posts/n_days,0)
first_day = min(as.Date(d$timestamp))
last_day = max(as.Date(d$timestamp))
```

We collected data from **`r n_outlets` news outlets** on TikTok and YouTube Shorts. Overall, these outlets published  **`r n_posts` posts**, or an average of **`r per_day` posts per day**.


## Basics 

```{r}
d |> 
  count(brand, platform, sort = T) |> 
  group_by(brand) |> 
  mutate(Posts = sum(n)) |> 
  spread(platform, n, fill = 0) |> 
  mutate(`TikTok (per day)` = TikTok/n_days,
         `YouTube (per day)` = `YouTube Shorts`/n_days) |> 
  mutate_if(is.numeric, round) |> 
  select(Outlet = brand, Posts, starts_with("TikTok"), starts_with("YouTube"))
```


## Publication patterns

## Content duplication
